version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: scci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../.env
    depends_on:
      - backend
    ports:
      - "3000:80"

  proxy:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"

volumes:
  db_data:
