version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: scci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  streamlit:
    build:
      context: ../streamlit_app
    env_file:
      - ../.env
    environment:
      BACKEND_URL: http://backend:4000
    depends_on:
      - backend
    ports:
      - "8501:8501"

  proxy:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - streamlit
    ports:
      - "8080:80"

volumes:
  db_data:
